### ISSUE TITLE
Remaining race conditions

### ISSUE THREAD

**Issue by emersion** [emersion/go-imap#151]
- [ ] client `imap.(*Conn).SetDebug()` (do we care?)
- [ ] client `imap.(*Conn).Upgrade()`
- [ ] client `client.(*Client).Authenticate()`
- [ ] server continuation requests
- [ ] server conn upgrade

**Comment by Neopallium** [comment]
I also found a race condition in client `client.(*Client).execute()`.  See PR #223 for a fix.

**Comment by Neopallium** [comment]
Also fixed the `server continuation request` data race in PR #223.

The lock in `server.(*conn)` really isn't needed anymore, as long as only one goroutine can write to the connection.  Also don't need a separate goroutine for writing continuations.

**Comment by Neopallium** [comment]
The `Upgrade()` data races need a better way to interrupt and block read/writes to the connection.

**Comment by emersion** [comment]
Yeah, the upgrade mechanism is a little involved. I wonder how we could make it better.

**Comment by Neopallium** [comment]
@emersion I have some code working to fix the upgrade data races.  Just need to clean it up before sending a PR.

Should be able to fix the `SetDebug()` data race too.  The client `SetDebug()` will need to send a `NOOP` command to unblock the reader goroutine.

**Comment by emersion** [comment]
Nice!

`SetDebug` is less important, because it shouldn't happen in production. Would still be nice to fix of course. Not sure what you mean by sending `NOOP`, I think I'm missing some context.

**Comment by Neopallium** [comment]
@emersion All remaining data races fixed in PR #223 .

To fix the `SetDebug()` data race we need to unblock the reader goroutine.  The only way I could think of to do that is to cause the server to send a response.  I used the upgrade logic and a `NOOP` command to fix the data race in `SetDebug()`.  Also added a `LockedWriter` to protect the debug `io.Writer` from concurrent writes.

For the `Authenicate` data race I added a `replies` channel for the auth response handler to pass the replies to the `client.execute()` method.  So only one goroutine is doing writes to the socket.
