### ISSUE TITLE
Force push (maybe?) causing compiling issues on prod environment.

### ISSUE THREAD

**Issue by arianitu** [emersion/go-imap#157]
We had this library pinned to commit `0109e79db691ad6f173063541188440234114a8d` which no longer seems to exist in this repo and our prod environment fails to compile this library.

I also can't check that commit to find a new commit to pin to since that seems to have been deleted from the history. I probably have to pin to a commit in v1 and hope for the best.

I'm not sure what happened on this side, but in the future, it's probably a good idea to *not* remove commits from this repo. 

Did someone force push this repo or something?

**Comment by arianitu** [comment]
Using `v1` causes compile issues. Can someone help me find the closest commit to `0109e79db691ad6f173063541188440234114a8d`?

**Comment by emersion** [comment]
Hi,

First of all, sorry for all the trouble.

I didn't force push to the repo, but here's what happened:
* The `master` branch contained the source code
* I wanted to cleanup the API, removing `imap.NewSeqSet` to prevent users from constructing a string when they wanted to create a new `imap.SeqSet` from integers. I pushed that to master, not breaking any promises because the master branch is marked as _instable_.
* I noticed some people complained that the API has changed. I then created two branches: `v0` with the old API, `v1` with the new API. I pushed new breaking changes to `v1`. `master` was still here, with one symbol changed from the old API, but not updated with new changes in `v1`. I pushed a commit to `master` saying "use the `v1` branch!".
* Time passed. `master` was still the default branch, but was very weird, having a half-changed API and not updated anymore. I decided to delete that branch, making the unstable `v1` branch the default one. I'm now in the process of stabilizing the API and release the first stable version.

So I think a fix for you would be either to pin to the last `v0` commit, or pin to one of the first commits in the `v1` branch. Pinning to `v0` seems more straightforward (but you may need to remove some calls to `NewSeqSet`). If you ever want to switch to `v1`, you can find the complete list of API changes here:  #152.

I'll try my best not to break compatibility in the future.
