### ISSUE TITLE
Implement UTF8=ACCEPT capability

### ISSUE THREAD

**Issue by emersion** [emersion/go-imap#16]
See https://tools.ietf.org/html/rfc6855

**Comment by foxcpp** [comment]
What needs to be done for it? From my understanding of linked RFC and go-imap internals, it needs to be supported by go-imap itself.
But since UTF8 extension relies on ENABLE to activate, we might need to merge go-imap-enable into go-imap for later to be able to properly handle `ENABLE UTF8=ACCEPT`.

**Comment by foxcpp** [comment]
Depends on #342 to get ENABLE extension in go-imap itself.
