### ISSUE TITLE
Unexpected line when parsing multipart messages

### ISSUE THREAD

**Issue by henryx** [emersion/go-imap#163]
Following the HOWTO in [wiki](https://github.com/emersion/go-imap/wiki/Fetching-messages) (keep in mind: is a bit outdated), I have this error:
```
multipart: unexpected line in Next(): "NTQtODYwYTcwZGYxOQ?t=x-123456789012-123456789012\r\n"
```
Analyzing the email, the string reported refers this piece of the email:
```
--__slack_1652905857__
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: quoted-printable
Content-Disposition: inline

Join a-team on Slack


a.â€‹coleague@a-team.â€‹invalid has invited you to join the Slack team
a-team.
Join now to start collaborating!

Join Now:
https://firstpartofthelinkNTQtODYwYTcwZGYxOQ?t=x-123456789012-123456789012


With Slack, you can message your team, share files, and get updates from
the other tools you use daily.
See Slack in action: https://slack.com/is

Team Name: a-team
Team URL: a-url.slack.com

--__slack_1652905857__
```

**Comment by emersion** [comment]
I think `mime/multipart` is confused about these characters: "a.â€". Since the text is using a `quoted-printable` encoding they shouldn't be here.

I've already heard of issues with Slack emails: https://github.com/emersion/go-message/issues/13

A Go patch is needed: https://github.com/golang/go/issues/22597
