### ISSUE TITLE
How to get only new emails

### ISSUE THREAD

**Issue by vkuznet** [emersion/go-imap#379]
HI,
I have followed examples in [example_test.go](https://github.com/emersion/go-imap/blob/master/client/example_test.go) of the client codebase and I can't find out how someone can get only new emails from the server. I was expecting to get flags along with a message by specifying FetchFlags item, but what I get back is always `\Seen` flag for all emails and I don't see any `\Recent` flags for emails which are new. Could you please clarify that?
Thanks,
Valentin.

**Comment by DeadNumbers** [comment]
Используйте критерий поиска `SearchCriteria.WithFlags`

**Comment by foxcpp** [comment]
\Recent flag is special and is only visible for the message on one session (from SELECT to disconnect or another SELECT).

Additionally, it might not be implemented by some servers (Gmail being a notable offender). What you might do instead is to save last UID and fetch all messages since that UID+1.

**Comment by foxcpp** [comment]
UID+1 you get anyway as UIDNEXT when selecting mailbox.

So:
1. Save UidNext.
2. On next run do Fetch of data you need for UIDNEXT:* seqset.

**Comment by vkuznet** [comment]
ok, thanks, closing the ticket then.
