### ISSUE TITLE
Example for MOVE

### ISSUE THREAD

**Issue by samstride** [emersion/go-imap#448]
Hi,

Thanks for maintaining this library.

I am trying to move a message from one mailbox to another and I can't figure it out.

Is it possible to add an example snippet towards the end of [this code on the wiki](https://github.com/emersion/go-imap/wiki/Fetching-messages)?

```go
.
.
.
// Process each message's part
for {
  .
  .
  .
}

// Move message from inbox to processed
.
.
.
```

Also, is it possible to create a new mailbox (if it does not exist)?

Thanks.

**Comment by emersion** [comment]
You shouldn't need to download the message at all. There's a MOVE command, see go-imap-move or:

https://github.com/emersion/go-imap/blob/231c001a28f54f599fe145a664d64871ed325b09/client/cmd_selected.go#L275

Closing since this isn't a question. Feel free to send a patch for `client/example_test.go`.

**Comment by samstride** [comment]
@emersion ,

I figured out what was wrong.

The current published release is `v1.1.0` which does not have `MOVE` feature.

I fixed it as follows:

```sh
go get github.com/emersion/go-imap@master

go get: upgraded github.com/emersion/go-imap v1.1.0 => v1.1.1-0.20210907175211-da05cbc268a8
```

Any chance of getting a release?

Ok, I will see if I can submit a patch.

Thanks for the assistance.

**Comment by G2G2G2G** [comment]
can someone give an example like the one on the front page readme for brainlets that can't figure out where to use 'move' like... m-my friend, totally not me. 

<del>I</del> My friend has several regexes that already separates all of the specified emails by their subjects correctly, just needs to move to the folders..
thanks

**Comment by samstride** [comment]
@G2G2G2G , the key is to find out folder names. In my use case, the mail server had the following names for folders.

```
INBOX (usual inbox)
INBOX.processed  (folder I move emails to after successful processing)
INBOX.errors  (folder I move emails to if I encounter errors during processing)
```

Then make sure you are using: `github.com/emersion/go-imap v1.2.0`

```go
// Connect to server

// Login

// Select INBOX

// Move
_ = c.move(seqSet, "INBOX.processed")
.
.
_ = c.move(seqSet, "INBOX.errors")

```

Hope that helps.

**Comment by G2G2G2G** [comment]
The example does that automatically and lists them all, I'm not sure how to use seqSet for each message after that

```Go
// Get the last 4 messages
	from := uint32(1)
	to := mbox.Messages
	if mbox.Messages > 3 {
		// We're using unsigned integers here, only subtract if the result is > 0
		from = mbox.Messages - 3
	}
	seqset := new(imap.SeqSet)
	seqset.AddRange(from, to)

	messages := make(chan *imap.Message, 10)
	done = make(chan error, 1)
	go func() {
		done <- c.Fetch(seqset, []imap.FetchItem{imap.FetchEnvelope}, messages)
	}()

	log.Println("Last 4 messages:")
	for msg := range messages {
		log.Println("* " + msg.Envelope.Subject)
	}
```
In the example all of them are printed out there in that msg := range area, I use my regex in there to get each type of message.. from there I want to send them to a folder but seqset seems to be set only once to something that remains the same and isn't message specific in the example case? idk

**Comment by samstride** [comment]
I do it like this:

```go
seqSet := new(imap.SeqSet)

for i := mbox.Messages; i >= 1; i-- {
    seqSet.AddNum(i)
    .
    .
    .
    // Move
    _ = c.move(seqSet, "INBOX.processed")
}
```

**Comment by G2G2G2G** [comment]
How do you get the subject in there to parse it, you have to make a channel etc inside of the for loop? doesn't seem like the proper way. There's no non channel function to just get a specific message number's data?
Also you're using "move" it should be "Move" from reading the program file he linked above, unless you set a boolean as the first input?

Search seems wrong for that too because it's just sorting by the switch statement not actually parsing the text in the files?
https://github.com/emersion/go-imap/blob/231c001a28f54f599fe145a664d64871ed325b09/search.go#L90

**Comment by G2G2G2G** [comment]
@emersion is there a way to use msg.Envelope.MessageId to move an email? that'd work in the main example easily..

**Comment by samstride** [comment]
@G2G2G2G , here is a snippet of how I do it when I am looking for an email from a specific sender with a specific subject.

```go
	// Select INBOX
	mailbox, err := c.Select("INBOX", false)
	if err != nil {
		log.Fataln(err)
	}

	if mailbox.Messages == 0 {
		log.Println("No messages in mailbox")
		return
	}

	seqSet := new(imap.SeqSet)

	for i := mailbox.Messages; i >= 1; i-- {
		seqSet.AddNum(i)

		// Get the whole message body
		var section imap.BodySectionName
		items := []imap.FetchItem{section.FetchItem()}

		messages := make(chan *imap.Message, 1)
		go func() {
			if err := c.Fetch(seqSet, items, messages); err != nil {
				log.Fataln(err)
			}
		}()

		msg := <-messages
		if msg == nil {
			log.Fatal("Server did not return any message")
		}

		body := msg.GetBody(&section)
		if body == nil {
			log.Fatal("Server did not return message body")
		}

		// Create a new mail reader
		mailReader, err := mail.CreateReader(body)
		if err != nil {
			log.Fatal(err)
		}

		// Process headers
		header := mailReader.Header

		emailTime, err := header.Date()
		if err != nil {
			log.Fatal(err)
		}

		from, err := header.AddressList("From")
		if err != nil {
			log.Fatal(err)
		}

                // Pin down sender
		if !strings.Contains(from[0].String(), "some sender") {
			log.Printf("Unrecognized sender: %s", from)
			// Move to other folder
			err = c.Move(seqSet, "INBOX.other")
			if err != nil {
				log.Fatal(err)
			}
			continue
		}

		// Pin down subject
		subject, err := header.Subject()
		if err != nil {
			log.Fatal(err)
		}
		if !strings.Contains(subject, "some subject") {
			log.Printf("Unrecognized subject: %s", subject)
			// Move to other folder
			err = c.Move(seqSet, "INBOX.other")
			if err != nil {
				log.Fatal(err)
			}
			continue
		}

		// Process each message's part
		for {
			mailPart, err := mailReader.NextPart()
			if err == io.EOF {
				break
			} else if err != nil {
				log.Fatal(err)
			}

			partHeader := mailPart.Header.(type)
			// Some processing
		}

		// Move message to processed folder
		err = c.Move(seqSet, "INBOX.processed")
		if err != nil {
			log.Println(err)
		}
	}
```

**Comment by G2G2G2G** [comment]
Yea mine seems better since you aren't running a channel inside of a for loop over and over

**Comment by Allendar** [comment]
I would like to ask something in addition to this. I'm using IMAP with Apple iCloud and use the example code and then loop through my `Junk` folder and try to move to the `Deleted Messages` folder, but I'm getting an error (probably from the Apple IMAP server?) that I can't find anything about on Google.

Here's the snippet of the code loop;

```
for msg := range messages {
	// spew.Dump(msg)

	// TODO :: Blacklist filter goes here for any Junk that can instantly be deleted for sure
	moveSeqset := new(imap.SeqSet)
	seqset.AddNum(msg.SeqNum)

	if err := c.Move(moveSeqset, "Deleted Messages"); err != nil {
		log.Fatal(errors.ErrorStack(err))
	}
}
```

The `Move` function returns this strange error, which doesn't seem to be part of this repo. Any idea if this is something Apple specific and how it might be resolved?

```
unexpected extra space between tokens
```

I'm sure the `Deleted Messages` is the correct mailbox name, because if I just call the messages by that name, then it works correctly.

Maybe Apple doesn't allow the `Move` command. If so; can I use another approach to still move/copy-delete messages?
