### ISSUE TITLE
Crash when parsing BODYSTRUCTURE

### ISSUE THREAD

**Issue by hartshorne** [emersion/go-imap#76]
Gmail is returning a BODYSTRUCTURE that looks like this:

    BODYSTRUCTURE (("TEXT" "PLAIN" ("CHARSET" "windows-1252") NIL NIL "QUOTED-PRINTABLE" 1406 39 NIL NIL NIL)("TEXT" "HTML" ("CHARSET" "windows-1252") NIL NIL "QUOTED-PRINTABLE" 5660 93 NIL NIL NIL) "ALTERNATIVE" ("BOUNDARY" "--NextPart_048F8BC8A2197DE2036A") NIL NIL))

The crash is in `func (bs *BodyStructure) Parse(fields []interface{}) error {` when it tries to grab a field that does not exist:

```go
  if location, ok := fields[end+3].([]interface{}); ok {
    bs.Location, _ = ParseStringList(location)
  }

```

Is that a valid BODYSTRUCTURE? A test like this (in message_test.go) will crash:

```go
  fields: []interface{}{
    []interface{}{"text", "plain", []interface{}{}, nil, nil, "us-ascii", "87", "22"},
    "alternative", []interface{}{"hello", "world"}, nil, nil,
  },
  bodyStructure: &BodyStructure{...},
```

I haven't really dug into the BODYSTRUCTURE spec, but go-imap shouldn't crash even if it gets invalid data.

**Comment by emersion** [comment]
Crashing when invalid data is received is a major issue. That was because of a wrong bound check, fixed in latest commit. Sorry about that!

[According to the RFC](https://tools.ietf.org/html/rfc3501#page-76), extension data for non-multipart messages contain 4 fields. Here GMail returns only 3. Maybe we should parse extension fields even if there are less than 4 of them?
